services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: shop-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: unless-stopped
  
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/1433'"]
      interval: 10s
      timeout: 5s
      retries: 30

  db-init:
    image: mcr.microsoft.com/mssql-tools18
    profiles: ["tools"]
    depends_on:
      - sqlserver
    volumes:
      - ./db:/scripts:ro
    environment:
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
    command: >
      bash -lc "
      echo 'Waiting for SQL Server...' &&
      for i in {1..60}; do
        /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P \"$MSSQL_SA_PASSWORD\" -Q \"SELECT 1\" -C && break
        sleep 2
      done &&
      echo 'Running DB script...' &&
      /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P \"$MSSQL_SA_PASSWORD\" -i /scripts/SQLQuery1.sql -C
      "

volumes:
  sql_data: