USE [master]
GO
/****** Object:  Database [HeThongBanHangThoiTrangDB]    Script Date: 2/26/2026 2:57:13 PM ******/
CREATE DATABASE [HeThongBanHangThoiTrangDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HeThongBanHangThoiTrangDB', FILENAME = N'/var/opt/mssql/data/HeThongBanHangThoiTrangDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HeThongBanHangThoiTrangDB_log', FILENAME = N'/var/opt/mssql/data/HeThongBanHangThoiTrangDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [HeThongBanHangThoiTrangDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HeThongBanHangThoiTrangDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [HeThongBanHangThoiTrangDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [HeThongBanHangThoiTrangDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [HeThongBanHangThoiTrangDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [HeThongBanHangThoiTrangDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [HeThongBanHangThoiTrangDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [HeThongBanHangThoiTrangDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [HeThongBanHangThoiTrangDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [HeThongBanHangThoiTrangDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [HeThongBanHangThoiTrangDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [HeThongBanHangThoiTrangDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [HeThongBanHangThoiTrangDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [HeThongBanHangThoiTrangDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [HeThongBanHangThoiTrangDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [HeThongBanHangThoiTrangDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [HeThongBanHangThoiTrangDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [HeThongBanHangThoiTrangDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [HeThongBanHangThoiTrangDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [HeThongBanHangThoiTrangDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [HeThongBanHangThoiTrangDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [HeThongBanHangThoiTrangDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [HeThongBanHangThoiTrangDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [HeThongBanHangThoiTrangDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [HeThongBanHangThoiTrangDB] SET RECOVERY FULL 
GO
ALTER DATABASE [HeThongBanHangThoiTrangDB] SET  MULTI_USER 
GO
ALTER DATABASE [HeThongBanHangThoiTrangDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [HeThongBanHangThoiTrangDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [HeThongBanHangThoiTrangDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [HeThongBanHangThoiTrangDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [HeThongBanHangThoiTrangDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [HeThongBanHangThoiTrangDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'HeThongBanHangThoiTrangDB', N'ON'
GO
ALTER DATABASE [HeThongBanHangThoiTrangDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [HeThongBanHangThoiTrangDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [HeThongBanHangThoiTrangDB]
GO
/****** Object:  Table [dbo].[SanPham]    Script Date: 2/26/2026 2:57:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SanPham](
	[MaSanPham] [int] IDENTITY(1,1) NOT NULL,
	[TenSanPham] [nvarchar](200) NOT NULL,
	[Slug] [varchar](200) NOT NULL,
	[MoTa] [nvarchar](max) NULL,
	[GiaGoc] [decimal](18, 2) NOT NULL,
	[MaDanhMuc] [int] NOT NULL,
	[AnhDaiDien] [varchar](500) NULL,
	[HoatDong] [bit] NOT NULL,
	[TaoLuc] [datetime2](0) NOT NULL,
	[CapNhatLuc] [datetime2](0) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaSanPham] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_SanPham_Slug] UNIQUE NONCLUSTERED 
(
	[Slug] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BienTheSanPham]    Script Date: 2/26/2026 2:57:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BienTheSanPham](
	[MaBienThe] [int] IDENTITY(1,1) NOT NULL,
	[MaSanPham] [int] NOT NULL,
	[MaMauSac] [int] NOT NULL,
	[MaKichCo] [int] NOT NULL,
	[SKU] [varchar](50) NOT NULL,
	[SoLuongTon] [int] NOT NULL,
	[DieuChinhGia] [decimal](18, 2) NOT NULL,
	[HoatDong] [bit] NOT NULL,
	[TaoLuc] [datetime2](0) NOT NULL,
	[CapNhatLuc] [datetime2](0) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaBienThe] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_BienTheSanPham_SKU] UNIQUE NONCLUSTERED 
(
	[SKU] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[vw_CanhBaoSapHetHang]    Script Date: 2/26/2026 2:57:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


/* =========================================================
   13) VIEW phuc vu Dashboard (tuy chon, khong bat buoc)
   ========================================================= */

-- Canh bao san pham sap het hang (tinh theo bien the)
CREATE VIEW [dbo].[vw_CanhBaoSapHetHang]
AS
SELECT
    sp.MaSanPham, sp.TenSanPham, sp.Slug,
    SUM(bt.SoLuongTon) AS TongTon
FROM dbo.SanPham sp
JOIN dbo.BienTheSanPham bt ON bt.MaSanPham = sp.MaSanPham
WHERE sp.HoatDong = 1 AND bt.HoatDong = 1
GROUP BY sp.MaSanPham, sp.TenSanPham, sp.Slug;

GO
/****** Object:  Table [dbo].[DonHang]    Script Date: 2/26/2026 2:57:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DonHang](
	[MaDonHang] [int] IDENTITY(1,1) NOT NULL,
	[MaDon] [varchar](20) NOT NULL,
	[MaNguoiDung] [int] NULL,
	[MaTrangThai] [int] NOT NULL,
	[NgayDat] [datetime2](0) NOT NULL,
	[TenNguoiNhan] [nvarchar](100) NOT NULL,
	[DiaChiGiaoHang] [nvarchar](500) NOT NULL,
	[SoDienThoaiNhan] [varchar](15) NOT NULL,
	[TongTien] [decimal](18, 2) NOT NULL,
	[TienGiam] [decimal](18, 2) NOT NULL,
	[PhiShip] [decimal](18, 2) NOT NULL,
	[ThanhTien]  AS (([TongTien]-[TienGiam])+[PhiShip]) PERSISTED,
	[MaMaGiamGia] [int] NULL,
	[CodeMaGiamGiaSnapshot] [varchar](50) NULL,
	[PhuongThucThanhToan] [varchar](50) NOT NULL,
	[TrangThaiThanhToan] [varchar](20) NOT NULL,
	[GhiChu] [nvarchar](500) NULL,
	[TaoLuc] [datetime2](0) NOT NULL,
	[CapNhatLuc] [datetime2](0) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaDonHang] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_DonHang_MaDon] UNIQUE NONCLUSTERED 
(
	[MaDon] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ChiTietDonHang]    Script Date: 2/26/2026 2:57:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ChiTietDonHang](
	[MaChiTiet] [int] IDENTITY(1,1) NOT NULL,
	[MaDonHang] [int] NOT NULL,
	[MaBienThe] [int] NOT NULL,
	[Snapshot_TenSanPham] [nvarchar](200) NOT NULL,
	[Snapshot_SKU] [varchar](50) NOT NULL,
	[Snapshot_Anh] [varchar](500) NULL,
	[SoLuong] [int] NOT NULL,
	[DonGia] [decimal](18, 2) NOT NULL,
	[ThanhTienDong]  AS ([SoLuong]*[DonGia]) PERSISTED,
PRIMARY KEY CLUSTERED 
(
	[MaChiTiet] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[vw_TopSanPhamBanChayTheoNgay]    Script Date: 2/26/2026 2:57:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- Top san pham ban chay theo ngay (dua tren ChiTietDonHang) - bo qua don DaHuy/ThatBai
CREATE VIEW [dbo].[vw_TopSanPhamBanChayTheoNgay]
AS
SELECT
    CAST(dh.NgayDat AS date) AS Ngay,
    ctdh.Snapshot_TenSanPham AS TenSanPham,
    SUM(ctdh.SoLuong) AS TongSoLuong
FROM dbo.DonHang dh
JOIN dbo.ChiTietDonHang ctdh ON ctdh.MaDonHang = dh.MaDonHang
WHERE dh.MaTrangThai IN (4) -- Thanh cong
GROUP BY CAST(dh.NgayDat AS date), ctdh.Snapshot_TenSanPham;

GO
/****** Object:  Table [dbo].[AnhSanPham]    Script Date: 2/26/2026 2:57:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AnhSanPham](
	[MaAnh] [int] IDENTITY(1,1) NOT NULL,
	[MaSanPham] [int] NOT NULL,
	[UrlAnh] [varchar](500) NOT NULL,
	[ThuTu] [int] NOT NULL,
	[AnhChinh] [bit] NOT NULL,
	[TaoLuc] [datetime2](0) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaAnh] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BaiViet]    Script Date: 2/26/2026 2:57:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BaiViet](
	[MaBaiViet] [int] IDENTITY(1,1) NOT NULL,
	[TieuDe] [nvarchar](255) NOT NULL,
	[Slug] [varchar](255) NOT NULL,
	[TomTat] [nvarchar](500) NULL,
	[NoiDung] [nvarchar](max) NULL,
	[AnhDaiDien] [varchar](500) NULL,
	[MaChuyenMuc] [int] NOT NULL,
	[DaXuatBan] [bit] NOT NULL,
	[XuatBanLuc] [datetime2](0) NULL,
	[TaoLuc] [datetime2](0) NOT NULL,
	[CapNhatLuc] [datetime2](0) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaBaiViet] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_BaiViet_Slug] UNIQUE NONCLUSTERED 
(
	[Slug] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BannerTrangChu]    Script Date: 2/26/2026 2:57:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BannerTrangChu](
	[MaBanner] [int] IDENTITY(1,1) NOT NULL,
	[UrlAnh] [nvarchar](500) NOT NULL,
	[TieuDe] [nvarchar](200) NULL,
	[UrlLienKet] [nvarchar](500) NULL,
	[KichHoat] [bit] NOT NULL,
	[ThuTu] [int] NOT NULL,
	[TaoLuc] [datetime2](0) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaBanner] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ChiTietGioHang]    Script Date: 2/26/2026 2:57:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ChiTietGioHang](
	[Ma] [int] IDENTITY(1,1) NOT NULL,
	[MaNguoiDung] [int] NOT NULL,
	[MaBienThe] [int] NOT NULL,
	[SoLuong] [int] NOT NULL,
	[TaoLuc] [datetime2](0) NOT NULL,
	[CapNhatLuc] [datetime2](0) NULL,
PRIMARY KEY CLUSTERED 
(
	[Ma] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ChiTietYeuThich]    Script Date: 2/26/2026 2:57:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ChiTietYeuThich](
	[Ma] [int] IDENTITY(1,1) NOT NULL,
	[MaDanhSach] [int] NOT NULL,
	[MaSanPham] [int] NOT NULL,
	[TaoLuc] [datetime2](0) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Ma] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_ChiTietYeuThich] UNIQUE NONCLUSTERED 
(
	[MaDanhSach] ASC,
	[MaSanPham] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ChuyenMucBaiViet]    Script Date: 2/26/2026 2:57:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ChuyenMucBaiViet](
	[MaChuyenMuc] [int] IDENTITY(1,1) NOT NULL,
	[TenChuyenMuc] [nvarchar](100) NOT NULL,
	[Slug] [varchar](100) NOT NULL,
	[TaoLuc] [datetime2](0) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaChuyenMuc] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_ChuyenMucBaiViet_Slug] UNIQUE NONCLUSTERED 
(
	[Slug] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DanhGiaSanPham]    Script Date: 2/26/2026 2:57:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DanhGiaSanPham](
	[MaDanhGia] [int] IDENTITY(1,1) NOT NULL,
	[MaSanPham] [int] NOT NULL,
	[MaNguoiDung] [int] NOT NULL,
	[MaDonHang] [int] NOT NULL,
	[SoSao] [int] NOT NULL,
	[NoiDung] [nvarchar](1000) NULL,
	[TaoLuc] [datetime2](0) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaDanhGia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DanhMuc]    Script Date: 2/26/2026 2:57:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DanhMuc](
	[MaDanhMuc] [int] IDENTITY(1,1) NOT NULL,
	[TenDanhMuc] [nvarchar](100) NOT NULL,
	[Slug] [varchar](100) NOT NULL,
	[MaDanhMucCha] [int] NULL,
	[HoatDong] [bit] NOT NULL,
	[TaoLuc] [datetime2](0) NOT NULL,
	[CapNhatLuc] [datetime2](0) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaDanhMuc] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_DanhMuc_Slug] UNIQUE NONCLUSTERED 
(
	[Slug] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DanhSachYeuThich]    Script Date: 2/26/2026 2:57:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DanhSachYeuThich](
	[MaDanhSach] [int] IDENTITY(1,1) NOT NULL,
	[MaNguoiDung] [int] NOT NULL,
	[TenDanhSach] [nvarchar](100) NOT NULL,
	[TaoLuc] [datetime2](0) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaDanhSach] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DiaChiNguoiDung]    Script Date: 2/26/2026 2:57:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DiaChiNguoiDung](
	[MaDiaChi] [int] IDENTITY(1,1) NOT NULL,
	[MaNguoiDung] [int] NOT NULL,
	[TenLienHe] [nvarchar](100) NOT NULL,
	[DienThoaiLienHe] [varchar](15) NOT NULL,
	[DiaChi] [nvarchar](255) NOT NULL,
	[TinhThanh] [nvarchar](50) NOT NULL,
	[QuanHuyen] [nvarchar](50) NOT NULL,
	[PhuongXa] [nvarchar](50) NOT NULL,
	[MacDinh] [bit] NOT NULL,
	[TaoLuc] [datetime2](0) NOT NULL,
	[CapNhatLuc] [datetime2](0) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaDiaChi] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DieuKienKhuyenMai]    Script Date: 2/26/2026 2:57:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DieuKienKhuyenMai](
	[MaDieuKien] [int] IDENTITY(1,1) NOT NULL,
	[MaKhuyenMai] [int] NOT NULL,
	[Truong] [varchar](50) NOT NULL,
	[ToanTu] [varchar](20) NOT NULL,
	[GiaTri] [nvarchar](200) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaDieuKien] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KhuyenMai]    Script Date: 2/26/2026 2:57:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KhuyenMai](
	[MaKhuyenMai] [int] IDENTITY(1,1) NOT NULL,
	[TenKhuyenMai] [nvarchar](200) NOT NULL,
	[LoaiGiamGia] [varchar](20) NOT NULL,
	[GiaTriGiam] [decimal](18, 2) NOT NULL,
	[GiamToiDa] [decimal](18, 2) NULL,
	[BatDau] [datetime2](0) NOT NULL,
	[KetThuc] [datetime2](0) NOT NULL,
	[KichHoat] [bit] NOT NULL,
	[UuTien] [int] NOT NULL,
	[TaoLuc] [datetime2](0) NOT NULL,
	[CapNhatLuc] [datetime2](0) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaKhuyenMai] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KichCo]    Script Date: 2/26/2026 2:57:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KichCo](
	[MaKichCo] [int] IDENTITY(1,1) NOT NULL,
	[TenKichCo] [varchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaKichCo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[TenKichCo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LichSuTrangThaiDonHang]    Script Date: 2/26/2026 2:57:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LichSuTrangThaiDonHang](
	[Ma] [int] IDENTITY(1,1) NOT NULL,
	[MaDonHang] [int] NOT NULL,
	[MaTrangThaiCu] [int] NULL,
	[MaTrangThaiMoi] [int] NOT NULL,
	[GhiChu] [nvarchar](255) NULL,
	[CapNhatBoiMaNguoiDung] [int] NULL,
	[ThoiGian] [datetime2](0) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Ma] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MaGiamGia]    Script Date: 2/26/2026 2:57:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MaGiamGia](
	[MaMaGiamGia] [int] IDENTITY(1,1) NOT NULL,
	[Code] [varchar](50) NOT NULL,
	[MaNguoiDung] [int] NULL,
	[MaKhuyenMai] [int] NOT NULL,
	[SoLanToiDa] [int] NOT NULL,
    [SoLanDaDung] [int] NOT NULL,
	[DaDung] [bit] NOT NULL,
	[DungLuc] [datetime2](0) NULL,
	[HetHanLuc] [datetime2](0) NOT NULL,
	[TaoLuc] [datetime2](0) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaMaGiamGia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_MaGiamGia_Code] UNIQUE NONCLUSTERED 
(
	[Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MauSac]    Script Date: 2/26/2026 2:57:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MauSac](
	[MaMauSac] [int] IDENTITY(1,1) NOT NULL,
	[TenMau] [nvarchar](50) NOT NULL,
	[MaHex] [varchar](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaMauSac] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[TenMau] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NguoiDung]    Script Date: 2/26/2026 2:57:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NguoiDung](
	[MaNguoiDung] [int] IDENTITY(1,1) NOT NULL,
	[TenDangNhap] [varchar](50) NULL,
	[MatKhauHash] [varchar](255) NULL,
	[Email] [varchar](100) NOT NULL,
	[GoogleId] [varchar](100) NULL,
	[NgaySinh] [date] NULL,
	[HoTen] [nvarchar](100) NOT NULL,
	[SoDienThoai] [varchar](15) NULL,
	[AnhDaiDien] [varchar](500) NULL,
	[MaVaiTro] [int] NOT NULL,
	[BiKhoa] [bit] NOT NULL,
	[TaoLuc] [datetime2](0) NOT NULL,
	[CapNhatLuc] [datetime2](0) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaNguoiDung] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_NguoiDung_Email] UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ProductPromotions]    Script Date: 2/26/2026 2:57:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ProductPromotions](
	[MaBienThe] [int] NOT NULL,
	[MaSanPham] [int] NOT NULL,
	[MaKhuyenMai] [int] NULL,
	[GiaGoc] [decimal](18, 2) NOT NULL,
	[SoTienGiam] [decimal](18, 2) NOT NULL,
	[GiaSauGiam] [decimal](18, 2) NOT NULL,
	[CapNhatLuc] [datetime2](0) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaBienThe] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SanPhamKhuyenMai]    Script Date: 2/26/2026 2:57:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SanPhamKhuyenMai](
	[Ma] [int] IDENTITY(1,1) NOT NULL,
	[MaSanPham] [int] NOT NULL,
	[MaKhuyenMai] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Ma] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_SanPhamKhuyenMai] UNIQUE NONCLUSTERED 
(
	[MaSanPham] ASC,
	[MaKhuyenMai] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ThongBao]    Script Date: 2/26/2026 2:57:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ThongBao](
	[MaThongBao] [int] IDENTITY(1,1) NOT NULL,
	[MaNguoiDung] [int] NOT NULL,
	[TieuDe] [nvarchar](200) NOT NULL,
	[NoiDung] [nvarchar](500) NOT NULL,
	[DaDoc] [bit] NOT NULL,
	[DocLuc] [datetime2](0) NULL,
	[Loai] [varchar](50) NULL,
	[TaoLuc] [datetime2](0) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaThongBao] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TrangThaiDonHang]    Script Date: 2/26/2026 2:57:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TrangThaiDonHang](
	[MaTrangThai] [int] NOT NULL,
	[TenTrangThai] [nvarchar](100) NOT NULL,
	[ThuTu] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaTrangThai] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[TenTrangThai] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VaiTro]    Script Date: 2/26/2026 2:57:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VaiTro](
	[MaVaiTro] [int] NOT NULL,
	[TenVaiTro] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaVaiTro] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[TenVaiTro] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_AnhSanPham_SanPham_ThuTu]    Script Date: 2/26/2026 2:57:13 PM ******/
CREATE NONCLUSTERED INDEX [IX_AnhSanPham_SanPham_ThuTu] ON [dbo].[AnhSanPham]
(
	[MaSanPham] ASC,
	[ThuTu] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [UX_AnhSanPham_AnhChinh_One]    Script Date: 2/26/2026 2:57:13 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UX_AnhSanPham_AnhChinh_One] ON [dbo].[AnhSanPham]
(
	[MaSanPham] ASC
)
WHERE ([AnhChinh]=(1))
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_BaiViet_CM_Published]    Script Date: 2/26/2026 2:57:13 PM ******/
CREATE NONCLUSTERED INDEX [IX_BaiViet_CM_Published] ON [dbo].[BaiViet]
(
	[MaChuyenMuc] ASC,
	[DaXuatBan] ASC,
	[XuatBanLuc] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_BannerTrangChu_Active_Sort]    Script Date: 2/26/2026 2:57:13 PM ******/
CREATE NONCLUSTERED INDEX [IX_BannerTrangChu_Active_Sort] ON [dbo].[BannerTrangChu]
(
	[KichHoat] ASC,
	[ThuTu] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_BienTheSanPham_MaSanPham]    Script Date: 2/26/2026 2:57:13 PM ******/
CREATE NONCLUSTERED INDEX [IX_BienTheSanPham_MaSanPham] ON [dbo].[BienTheSanPham]
(
	[MaSanPham] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [UX_BienTheSanPham_Combo]    Script Date: 2/26/2026 2:57:13 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UX_BienTheSanPham_Combo] ON [dbo].[BienTheSanPham]
(
	[MaSanPham] ASC,
	[MaMauSac] ASC,
	[MaKichCo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_ChiTietDonHang_MaDonHang]    Script Date: 2/26/2026 2:57:13 PM ******/
CREATE NONCLUSTERED INDEX [IX_ChiTietDonHang_MaDonHang] ON [dbo].[ChiTietDonHang]
(
	[MaDonHang] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [UX_ChiTietGioHang_User_Variant]    Script Date: 2/26/2026 2:57:13 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UX_ChiTietGioHang_User_Variant] ON [dbo].[ChiTietGioHang]
(
	[MaNguoiDung] ASC,
	[MaBienThe] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_ChiTietYeuThich_SanPham]    Script Date: 2/26/2026 2:57:13 PM ******/
CREATE NONCLUSTERED INDEX [IX_ChiTietYeuThich_SanPham] ON [dbo].[ChiTietYeuThich]
(
	[MaSanPham] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_DanhGiaSanPham_Product_Date]    Script Date: 2/26/2026 2:57:13 PM ******/
CREATE NONCLUSTERED INDEX [IX_DanhGiaSanPham_Product_Date] ON [dbo].[DanhGiaSanPham]
(
	[MaSanPham] ASC,
	[TaoLuc] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [UX_DanhGiaSanPham_Order_Product]    Script Date: 2/26/2026 2:57:13 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UX_DanhGiaSanPham_Order_Product] ON [dbo].[DanhGiaSanPham]
(
	[MaDonHang] ASC,
	[MaSanPham] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_DanhMuc_Cha]    Script Date: 2/26/2026 2:57:13 PM ******/
CREATE NONCLUSTERED INDEX [IX_DanhMuc_Cha] ON [dbo].[DanhMuc]
(
	[MaDanhMucCha] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_DiaChiNguoiDung_MaNguoiDung]    Script Date: 2/26/2026 2:57:13 PM ******/
CREATE NONCLUSTERED INDEX [IX_DiaChiNguoiDung_MaNguoiDung] ON [dbo].[DiaChiNguoiDung]
(
	[MaNguoiDung] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [UX_DiaChiNguoiDung_MacDinh]    Script Date: 2/26/2026 2:57:13 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UX_DiaChiNguoiDung_MacDinh] ON [dbo].[DiaChiNguoiDung]
(
	[MaNguoiDung] ASC
)
WHERE ([MacDinh]=(1))
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_DieuKienKhuyenMai_MaKhuyenMai]    Script Date: 2/26/2026 2:57:13 PM ******/
CREATE NONCLUSTERED INDEX [IX_DieuKienKhuyenMai_MaKhuyenMai] ON [dbo].[DieuKienKhuyenMai]
(
	[MaKhuyenMai] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_DonHang_Status_Date]    Script Date: 2/26/2026 2:57:13 PM ******/
CREATE NONCLUSTERED INDEX [IX_DonHang_Status_Date] ON [dbo].[DonHang]
(
	[MaTrangThai] ASC,
	[NgayDat] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_DonHang_User_Date]    Script Date: 2/26/2026 2:57:13 PM ******/
CREATE NONCLUSTERED INDEX [IX_DonHang_User_Date] ON [dbo].[DonHang]
(
	[MaNguoiDung] ASC,
	[NgayDat] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_KhuyenMai_ActiveDate]    Script Date: 2/26/2026 2:57:13 PM ******/
CREATE NONCLUSTERED INDEX [IX_KhuyenMai_ActiveDate] ON [dbo].[KhuyenMai]
(
	[KichHoat] ASC,
	[BatDau] ASC,
	[KetThuc] ASC,
	[UuTien] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_LichSuTrangThaiDonHang_Order_Time]    Script Date: 2/26/2026 2:57:13 PM ******/
CREATE NONCLUSTERED INDEX [IX_LichSuTrangThaiDonHang_Order_Time] ON [dbo].[LichSuTrangThaiDonHang]
(
	[MaDonHang] ASC,
	[ThoiGian] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_MaGiamGia_User_Usage]    Script Date: 2/26/2026 2:57:13 PM ******/
CREATE NONCLUSTERED INDEX [IX_MaGiamGia_User_Usage] ON [dbo].[MaGiamGia]
(
	[MaNguoiDung] ASC,
	[SoLanDaDung] ASC,
    [SoLanToiDa] ASC,
	[HetHanLuc] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UX_NguoiDung_GoogleId_NotNull]    Script Date: 2/26/2026 2:57:13 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UX_NguoiDung_GoogleId_NotNull] ON [dbo].[NguoiDung]
(
	[GoogleId] ASC
)
WHERE ([GoogleId] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UX_NguoiDung_TenDangNhap_NotNull]    Script Date: 2/26/2026 2:57:13 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UX_NguoiDung_TenDangNhap_NotNull] ON [dbo].[NguoiDung]
(
	[TenDangNhap] ASC
)
WHERE ([TenDangNhap] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_ProductPromotions_MaKhuyenMai]    Script Date: 2/26/2026 2:57:13 PM ******/
CREATE NONCLUSTERED INDEX [IX_ProductPromotions_MaKhuyenMai] ON [dbo].[ProductPromotions]
(
	[MaKhuyenMai] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_ProductPromotions_MaSanPham]    Script Date: 2/26/2026 2:57:13 PM ******/
CREATE NONCLUSTERED INDEX [IX_ProductPromotions_MaSanPham] ON [dbo].[ProductPromotions]
(
	[MaSanPham] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_SanPham_DanhMuc]    Script Date: 2/26/2026 2:57:13 PM ******/
CREATE NONCLUSTERED INDEX [IX_SanPham_DanhMuc] ON [dbo].[SanPham]
(
	[MaDanhMuc] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_SanPham_HoatDong]    Script Date: 2/26/2026 2:57:13 PM ******/
CREATE NONCLUSTERED INDEX [IX_SanPham_HoatDong] ON [dbo].[SanPham]
(
	[HoatDong] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_SanPhamKhuyenMai_MaKhuyenMai]    Script Date: 2/26/2026 2:57:13 PM ******/
CREATE NONCLUSTERED INDEX [IX_SanPhamKhuyenMai_MaKhuyenMai] ON [dbo].[SanPhamKhuyenMai]
(
	[MaKhuyenMai] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_ThongBao_User_Read]    Script Date: 2/26/2026 2:57:13 PM ******/
CREATE NONCLUSTERED INDEX [IX_ThongBao_User_Read] ON [dbo].[ThongBao]
(
	[MaNguoiDung] ASC,
	[DaDoc] ASC,
	[TaoLuc] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [UX_TrangThaiDonHang_ThuTu]    Script Date: 2/26/2026 2:57:13 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UX_TrangThaiDonHang_ThuTu] ON [dbo].[TrangThaiDonHang]
(
	[ThuTu] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AnhSanPham] ADD  CONSTRAINT [DF_AnhSanPham_ThuTu]  DEFAULT ((0)) FOR [ThuTu]
GO
ALTER TABLE [dbo].[AnhSanPham] ADD  CONSTRAINT [DF_AnhSanPham_AnhChinh]  DEFAULT ((0)) FOR [AnhChinh]
GO
ALTER TABLE [dbo].[AnhSanPham] ADD  CONSTRAINT [DF_AnhSanPham_TaoLuc]  DEFAULT (sysutcdatetime()) FOR [TaoLuc]
GO
ALTER TABLE [dbo].[BaiViet] ADD  CONSTRAINT [DF_BaiViet_DaXuatBan]  DEFAULT ((0)) FOR [DaXuatBan]
GO
ALTER TABLE [dbo].[BaiViet] ADD  CONSTRAINT [DF_BaiViet_TaoLuc]  DEFAULT (sysutcdatetime()) FOR [TaoLuc]
GO
ALTER TABLE [dbo].[BannerTrangChu] ADD  CONSTRAINT [DF_BannerTrangChu_KichHoat]  DEFAULT ((1)) FOR [KichHoat]
GO
ALTER TABLE [dbo].[BannerTrangChu] ADD  CONSTRAINT [DF_BannerTrangChu_ThuTu]  DEFAULT ((0)) FOR [ThuTu]
GO
ALTER TABLE [dbo].[BannerTrangChu] ADD  CONSTRAINT [DF_BannerTrangChu_TaoLuc]  DEFAULT (sysutcdatetime()) FOR [TaoLuc]
GO
ALTER TABLE [dbo].[BienTheSanPham] ADD  CONSTRAINT [DF_BienTheSanPham_SoLuongTon]  DEFAULT ((0)) FOR [SoLuongTon]
GO
ALTER TABLE [dbo].[BienTheSanPham] ADD  CONSTRAINT [DF_BienTheSanPham_DieuChinhGia]  DEFAULT ((0)) FOR [DieuChinhGia]
GO
ALTER TABLE [dbo].[BienTheSanPham] ADD  CONSTRAINT [DF_BienTheSanPham_HoatDong]  DEFAULT ((1)) FOR [HoatDong]
GO
ALTER TABLE [dbo].[BienTheSanPham] ADD  CONSTRAINT [DF_BienTheSanPham_TaoLuc]  DEFAULT (sysutcdatetime()) FOR [TaoLuc]
GO
ALTER TABLE [dbo].[ChiTietGioHang] ADD  CONSTRAINT [DF_ChiTietGioHang_SoLuong]  DEFAULT ((1)) FOR [SoLuong]
GO
ALTER TABLE [dbo].[ChiTietGioHang] ADD  CONSTRAINT [DF_ChiTietGioHang_TaoLuc]  DEFAULT (sysutcdatetime()) FOR [TaoLuc]
GO
ALTER TABLE [dbo].[ChiTietYeuThich] ADD  CONSTRAINT [DF_ChiTietYeuThich_TaoLuc]  DEFAULT (sysutcdatetime()) FOR [TaoLuc]
GO
ALTER TABLE [dbo].[ChuyenMucBaiViet] ADD  CONSTRAINT [DF_ChuyenMucBaiViet_TaoLuc]  DEFAULT (sysutcdatetime()) FOR [TaoLuc]
GO
ALTER TABLE [dbo].[DanhGiaSanPham] ADD  CONSTRAINT [DF_DanhGiaSanPham_TaoLuc]  DEFAULT (sysutcdatetime()) FOR [TaoLuc]
GO
ALTER TABLE [dbo].[DanhMuc] ADD  CONSTRAINT [DF_DanhMuc_HoatDong]  DEFAULT ((1)) FOR [HoatDong]
GO
ALTER TABLE [dbo].[DanhMuc] ADD  CONSTRAINT [DF_DanhMuc_TaoLuc]  DEFAULT (sysutcdatetime()) FOR [TaoLuc]
GO
ALTER TABLE [dbo].[DanhSachYeuThich] ADD  CONSTRAINT [DF_DanhSachYeuThich_Ten]  DEFAULT (N'Yeu thich') FOR [TenDanhSach]
GO
ALTER TABLE [dbo].[DanhSachYeuThich] ADD  CONSTRAINT [DF_DanhSachYeuThich_TaoLuc]  DEFAULT (sysutcdatetime()) FOR [TaoLuc]
GO
ALTER TABLE [dbo].[DiaChiNguoiDung] ADD  CONSTRAINT [DF_DiaChiNguoiDung_MacDinh]  DEFAULT ((0)) FOR [MacDinh]
GO
ALTER TABLE [dbo].[DiaChiNguoiDung] ADD  CONSTRAINT [DF_DiaChiNguoiDung_TaoLuc]  DEFAULT (sysutcdatetime()) FOR [TaoLuc]
GO
ALTER TABLE [dbo].[DonHang] ADD  CONSTRAINT [DF_DonHang_MaTrangThai]  DEFAULT ((1)) FOR [MaTrangThai]
GO
ALTER TABLE [dbo].[DonHang] ADD  CONSTRAINT [DF_DonHang_NgayDat]  DEFAULT (sysutcdatetime()) FOR [NgayDat]
GO
ALTER TABLE [dbo].[DonHang] ADD  CONSTRAINT [DF_DonHang_TongTien]  DEFAULT ((0)) FOR [TongTien]
GO
ALTER TABLE [dbo].[DonHang] ADD  CONSTRAINT [DF_DonHang_TienGiam]  DEFAULT ((0)) FOR [TienGiam]
GO
ALTER TABLE [dbo].[DonHang] ADD  CONSTRAINT [DF_DonHang_PhiShip]  DEFAULT ((0)) FOR [PhiShip]
GO
ALTER TABLE [dbo].[DonHang] ADD  CONSTRAINT [DF_DonHang_TrangThaiTT]  DEFAULT ('Unpaid') FOR [TrangThaiThanhToan]
GO
ALTER TABLE [dbo].[DonHang] ADD  CONSTRAINT [DF_DonHang_TaoLuc]  DEFAULT (sysutcdatetime()) FOR [TaoLuc]
GO
ALTER TABLE [dbo].[KhuyenMai] ADD  CONSTRAINT [DF_KhuyenMai_KichHoat]  DEFAULT ((1)) FOR [KichHoat]
GO
ALTER TABLE [dbo].[KhuyenMai] ADD  CONSTRAINT [DF_KhuyenMai_UuTien]  DEFAULT ((0)) FOR [UuTien]
GO
ALTER TABLE [dbo].[KhuyenMai] ADD  CONSTRAINT [DF_KhuyenMai_TaoLuc]  DEFAULT (sysutcdatetime()) FOR [TaoLuc]
GO
ALTER TABLE [dbo].[LichSuTrangThaiDonHang] ADD  CONSTRAINT [DF_LichSuTrangThaiDonHang_ThoiGian]  DEFAULT (sysutcdatetime()) FOR [ThoiGian]
GO
ALTER TABLE [dbo].[MaGiamGia] ADD  CONSTRAINT [DF_MaGiamGia_SoLanToiDa]  DEFAULT ((1)) FOR [SoLanToiDa]
GO
ALTER TABLE [dbo].[MaGiamGia] ADD  CONSTRAINT [DF_MaGiamGia_SoLanDaDung]  DEFAULT ((0)) FOR [SoLanDaDung]
GO
ALTER TABLE [dbo].[MaGiamGia] ADD  CONSTRAINT [DF_MaGiamGia_DaDung]  DEFAULT ((0)) FOR [DaDung]
GO
ALTER TABLE [dbo].[MaGiamGia] ADD  CONSTRAINT [DF_MaGiamGia_TaoLuc]  DEFAULT (sysutcdatetime()) FOR [TaoLuc]
GO
ALTER TABLE [dbo].[NguoiDung] ADD  CONSTRAINT [DF_NguoiDung_MaVaiTro]  DEFAULT ((2)) FOR [MaVaiTro]
GO
ALTER TABLE [dbo].[NguoiDung] ADD  CONSTRAINT [DF_NguoiDung_BiKhoa]  DEFAULT ((0)) FOR [BiKhoa]
GO
ALTER TABLE [dbo].[NguoiDung] ADD  CONSTRAINT [DF_NguoiDung_TaoLuc]  DEFAULT (sysutcdatetime()) FOR [TaoLuc]
GO
ALTER TABLE [dbo].[SanPham] ADD  CONSTRAINT [DF_SanPham_HoatDong]  DEFAULT ((1)) FOR [HoatDong]
GO
ALTER TABLE [dbo].[SanPham] ADD  CONSTRAINT [DF_SanPham_TaoLuc]  DEFAULT (sysutcdatetime()) FOR [TaoLuc]
GO
ALTER TABLE [dbo].[ThongBao] ADD  CONSTRAINT [DF_ThongBao_DaDoc]  DEFAULT ((0)) FOR [DaDoc]
GO
ALTER TABLE [dbo].[ThongBao] ADD  CONSTRAINT [DF_ThongBao_TaoLuc]  DEFAULT (sysutcdatetime()) FOR [TaoLuc]
GO
ALTER TABLE [dbo].[AnhSanPham]  WITH CHECK ADD  CONSTRAINT [FK_AnhSanPham_SanPham] FOREIGN KEY([MaSanPham])
REFERENCES [dbo].[SanPham] ([MaSanPham])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AnhSanPham] CHECK CONSTRAINT [FK_AnhSanPham_SanPham]
GO
ALTER TABLE [dbo].[BaiViet]  WITH CHECK ADD  CONSTRAINT [FK_BaiViet_ChuyenMuc] FOREIGN KEY([MaChuyenMuc])
REFERENCES [dbo].[ChuyenMucBaiViet] ([MaChuyenMuc])
GO
ALTER TABLE [dbo].[BaiViet] CHECK CONSTRAINT [FK_BaiViet_ChuyenMuc]
GO
ALTER TABLE [dbo].[BienTheSanPham]  WITH CHECK ADD  CONSTRAINT [FK_BienTheSanPham_KichCo] FOREIGN KEY([MaKichCo])
REFERENCES [dbo].[KichCo] ([MaKichCo])
GO
ALTER TABLE [dbo].[BienTheSanPham] CHECK CONSTRAINT [FK_BienTheSanPham_KichCo]
GO
ALTER TABLE [dbo].[BienTheSanPham]  WITH CHECK ADD  CONSTRAINT [FK_BienTheSanPham_MauSac] FOREIGN KEY([MaMauSac])
REFERENCES [dbo].[MauSac] ([MaMauSac])
GO
ALTER TABLE [dbo].[BienTheSanPham] CHECK CONSTRAINT [FK_BienTheSanPham_MauSac]
GO
ALTER TABLE [dbo].[BienTheSanPham]  WITH CHECK ADD  CONSTRAINT [FK_BienTheSanPham_SanPham] FOREIGN KEY([MaSanPham])
REFERENCES [dbo].[SanPham] ([MaSanPham])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[BienTheSanPham] CHECK CONSTRAINT [FK_BienTheSanPham_SanPham]
GO
ALTER TABLE [dbo].[ChiTietDonHang]  WITH CHECK ADD  CONSTRAINT [FK_ChiTietDonHang_BienThe] FOREIGN KEY([MaBienThe])
REFERENCES [dbo].[BienTheSanPham] ([MaBienThe])
GO
ALTER TABLE [dbo].[ChiTietDonHang] CHECK CONSTRAINT [FK_ChiTietDonHang_BienThe]
GO
ALTER TABLE [dbo].[ChiTietDonHang]  WITH CHECK ADD  CONSTRAINT [FK_ChiTietDonHang_DonHang] FOREIGN KEY([MaDonHang])
REFERENCES [dbo].[DonHang] ([MaDonHang])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ChiTietDonHang] CHECK CONSTRAINT [FK_ChiTietDonHang_DonHang]
GO
ALTER TABLE [dbo].[ChiTietGioHang]  WITH CHECK ADD  CONSTRAINT [FK_ChiTietGioHang_BienThe] FOREIGN KEY([MaBienThe])
REFERENCES [dbo].[BienTheSanPham] ([MaBienThe])
GO
ALTER TABLE [dbo].[ChiTietGioHang] CHECK CONSTRAINT [FK_ChiTietGioHang_BienThe]
GO
ALTER TABLE [dbo].[ChiTietGioHang]  WITH CHECK ADD  CONSTRAINT [FK_ChiTietGioHang_NguoiDung] FOREIGN KEY([MaNguoiDung])
REFERENCES [dbo].[NguoiDung] ([MaNguoiDung])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ChiTietGioHang] CHECK CONSTRAINT [FK_ChiTietGioHang_NguoiDung]
GO
ALTER TABLE [dbo].[ChiTietYeuThich]  WITH CHECK ADD  CONSTRAINT [FK_ChiTietYeuThich_DanhSach] FOREIGN KEY([MaDanhSach])
REFERENCES [dbo].[DanhSachYeuThich] ([MaDanhSach])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ChiTietYeuThich] CHECK CONSTRAINT [FK_ChiTietYeuThich_DanhSach]
GO
ALTER TABLE [dbo].[ChiTietYeuThich]  WITH CHECK ADD  CONSTRAINT [FK_ChiTietYeuThich_SanPham] FOREIGN KEY([MaSanPham])
REFERENCES [dbo].[SanPham] ([MaSanPham])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ChiTietYeuThich] CHECK CONSTRAINT [FK_ChiTietYeuThich_SanPham]
GO
ALTER TABLE [dbo].[DanhGiaSanPham]  WITH CHECK ADD  CONSTRAINT [FK_DanhGiaSanPham_DonHang] FOREIGN KEY([MaDonHang])
REFERENCES [dbo].[DonHang] ([MaDonHang])
GO
ALTER TABLE [dbo].[DanhGiaSanPham] CHECK CONSTRAINT [FK_DanhGiaSanPham_DonHang]
GO
ALTER TABLE [dbo].[DanhGiaSanPham]  WITH CHECK ADD  CONSTRAINT [FK_DanhGiaSanPham_NguoiDung] FOREIGN KEY([MaNguoiDung])
REFERENCES [dbo].[NguoiDung] ([MaNguoiDung])
GO
ALTER TABLE [dbo].[DanhGiaSanPham] CHECK CONSTRAINT [FK_DanhGiaSanPham_NguoiDung]
GO
ALTER TABLE [dbo].[DanhGiaSanPham]  WITH CHECK ADD  CONSTRAINT [FK_DanhGiaSanPham_SanPham] FOREIGN KEY([MaSanPham])
REFERENCES [dbo].[SanPham] ([MaSanPham])
GO
ALTER TABLE [dbo].[DanhGiaSanPham] CHECK CONSTRAINT [FK_DanhGiaSanPham_SanPham]
GO
ALTER TABLE [dbo].[DanhMuc]  WITH CHECK ADD  CONSTRAINT [FK_DanhMuc_Cha] FOREIGN KEY([MaDanhMucCha])
REFERENCES [dbo].[DanhMuc] ([MaDanhMuc])
GO
ALTER TABLE [dbo].[DanhMuc] CHECK CONSTRAINT [FK_DanhMuc_Cha]
GO
ALTER TABLE [dbo].[DanhSachYeuThich]  WITH CHECK ADD  CONSTRAINT [FK_DanhSachYeuThich_NguoiDung] FOREIGN KEY([MaNguoiDung])
REFERENCES [dbo].[NguoiDung] ([MaNguoiDung])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[DanhSachYeuThich] CHECK CONSTRAINT [FK_DanhSachYeuThich_NguoiDung]
GO
ALTER TABLE [dbo].[DiaChiNguoiDung]  WITH CHECK ADD  CONSTRAINT [FK_DiaChiNguoiDung_NguoiDung] FOREIGN KEY([MaNguoiDung])
REFERENCES [dbo].[NguoiDung] ([MaNguoiDung])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[DiaChiNguoiDung] CHECK CONSTRAINT [FK_DiaChiNguoiDung_NguoiDung]
GO
ALTER TABLE [dbo].[DieuKienKhuyenMai]  WITH CHECK ADD  CONSTRAINT [FK_DieuKienKhuyenMai_KhuyenMai] FOREIGN KEY([MaKhuyenMai])
REFERENCES [dbo].[KhuyenMai] ([MaKhuyenMai])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[DieuKienKhuyenMai] CHECK CONSTRAINT [FK_DieuKienKhuyenMai_KhuyenMai]
GO
ALTER TABLE [dbo].[DonHang]  WITH CHECK ADD  CONSTRAINT [FK_DonHang_MaGiamGia] FOREIGN KEY([MaMaGiamGia])
REFERENCES [dbo].[MaGiamGia] ([MaMaGiamGia])
GO
ALTER TABLE [dbo].[DonHang] CHECK CONSTRAINT [FK_DonHang_MaGiamGia]
GO
ALTER TABLE [dbo].[DonHang]  WITH CHECK ADD  CONSTRAINT [FK_DonHang_NguoiDung] FOREIGN KEY([MaNguoiDung])
REFERENCES [dbo].[NguoiDung] ([MaNguoiDung])
GO
ALTER TABLE [dbo].[DonHang] CHECK CONSTRAINT [FK_DonHang_NguoiDung]
GO
ALTER TABLE [dbo].[DonHang]  WITH CHECK ADD  CONSTRAINT [FK_DonHang_TrangThai] FOREIGN KEY([MaTrangThai])
REFERENCES [dbo].[TrangThaiDonHang] ([MaTrangThai])
GO
ALTER TABLE [dbo].[DonHang] CHECK CONSTRAINT [FK_DonHang_TrangThai]
GO
ALTER TABLE [dbo].[LichSuTrangThaiDonHang]  WITH CHECK ADD  CONSTRAINT [FK_LichSuTrangThaiDonHang_CapNhatBoi] FOREIGN KEY([CapNhatBoiMaNguoiDung])
REFERENCES [dbo].[NguoiDung] ([MaNguoiDung])
GO
ALTER TABLE [dbo].[LichSuTrangThaiDonHang] CHECK CONSTRAINT [FK_LichSuTrangThaiDonHang_CapNhatBoi]
GO
ALTER TABLE [dbo].[LichSuTrangThaiDonHang]  WITH CHECK ADD  CONSTRAINT [FK_LichSuTrangThaiDonHang_Cu] FOREIGN KEY([MaTrangThaiCu])
REFERENCES [dbo].[TrangThaiDonHang] ([MaTrangThai])
GO
ALTER TABLE [dbo].[LichSuTrangThaiDonHang] CHECK CONSTRAINT [FK_LichSuTrangThaiDonHang_Cu]
GO
ALTER TABLE [dbo].[LichSuTrangThaiDonHang]  WITH CHECK ADD  CONSTRAINT [FK_LichSuTrangThaiDonHang_DonHang] FOREIGN KEY([MaDonHang])
REFERENCES [dbo].[DonHang] ([MaDonHang])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[LichSuTrangThaiDonHang] CHECK CONSTRAINT [FK_LichSuTrangThaiDonHang_DonHang]
GO
ALTER TABLE [dbo].[LichSuTrangThaiDonHang]  WITH CHECK ADD  CONSTRAINT [FK_LichSuTrangThaiDonHang_Moi] FOREIGN KEY([MaTrangThaiMoi])
REFERENCES [dbo].[TrangThaiDonHang] ([MaTrangThai])
GO
ALTER TABLE [dbo].[LichSuTrangThaiDonHang] CHECK CONSTRAINT [FK_LichSuTrangThaiDonHang_Moi]
GO
ALTER TABLE [dbo].[MaGiamGia]  WITH CHECK ADD  CONSTRAINT [FK_MaGiamGia_KhuyenMai] FOREIGN KEY([MaKhuyenMai])
REFERENCES [dbo].[KhuyenMai] ([MaKhuyenMai])
GO
ALTER TABLE [dbo].[MaGiamGia] CHECK CONSTRAINT [FK_MaGiamGia_KhuyenMai]
GO
ALTER TABLE [dbo].[MaGiamGia]  WITH CHECK ADD  CONSTRAINT [FK_MaGiamGia_NguoiDung] FOREIGN KEY([MaNguoiDung])
REFERENCES [dbo].[NguoiDung] ([MaNguoiDung])
GO
ALTER TABLE [dbo].[MaGiamGia] CHECK CONSTRAINT [FK_MaGiamGia_NguoiDung]
GO
ALTER TABLE [dbo].[NguoiDung]  WITH CHECK ADD  CONSTRAINT [FK_NguoiDung_VaiTro] FOREIGN KEY([MaVaiTro])
REFERENCES [dbo].[VaiTro] ([MaVaiTro])
GO
ALTER TABLE [dbo].[NguoiDung] CHECK CONSTRAINT [FK_NguoiDung_VaiTro]
GO
ALTER TABLE [dbo].[ProductPromotions]  WITH CHECK ADD  CONSTRAINT [FK_PP_BienThe] FOREIGN KEY([MaBienThe])
REFERENCES [dbo].[BienTheSanPham] ([MaBienThe])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ProductPromotions] CHECK CONSTRAINT [FK_PP_BienThe]
GO
ALTER TABLE [dbo].[ProductPromotions]  WITH CHECK ADD  CONSTRAINT [FK_PP_KhuyenMai] FOREIGN KEY([MaKhuyenMai])
REFERENCES [dbo].[KhuyenMai] ([MaKhuyenMai])
GO
ALTER TABLE [dbo].[ProductPromotions] CHECK CONSTRAINT [FK_PP_KhuyenMai]
GO
ALTER TABLE [dbo].[ProductPromotions]  WITH CHECK ADD  CONSTRAINT [FK_PP_SanPham] FOREIGN KEY([MaSanPham])
REFERENCES [dbo].[SanPham] ([MaSanPham])
GO
ALTER TABLE [dbo].[ProductPromotions] CHECK CONSTRAINT [FK_PP_SanPham]
GO
ALTER TABLE [dbo].[SanPham]  WITH CHECK ADD  CONSTRAINT [FK_SanPham_DanhMuc] FOREIGN KEY([MaDanhMuc])
REFERENCES [dbo].[DanhMuc] ([MaDanhMuc])
GO
ALTER TABLE [dbo].[SanPham] CHECK CONSTRAINT [FK_SanPham_DanhMuc]
GO
ALTER TABLE [dbo].[SanPhamKhuyenMai]  WITH CHECK ADD  CONSTRAINT [FK_SanPhamKhuyenMai_KhuyenMai] FOREIGN KEY([MaKhuyenMai])
REFERENCES [dbo].[KhuyenMai] ([MaKhuyenMai])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[SanPhamKhuyenMai] CHECK CONSTRAINT [FK_SanPhamKhuyenMai_KhuyenMai]
GO
ALTER TABLE [dbo].[SanPhamKhuyenMai]  WITH CHECK ADD  CONSTRAINT [FK_SanPhamKhuyenMai_SanPham] FOREIGN KEY([MaSanPham])
REFERENCES [dbo].[SanPham] ([MaSanPham])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[SanPhamKhuyenMai] CHECK CONSTRAINT [FK_SanPhamKhuyenMai_SanPham]
GO
ALTER TABLE [dbo].[ThongBao]  WITH CHECK ADD  CONSTRAINT [FK_ThongBao_NguoiDung] FOREIGN KEY([MaNguoiDung])
REFERENCES [dbo].[NguoiDung] ([MaNguoiDung])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ThongBao] CHECK CONSTRAINT [FK_ThongBao_NguoiDung]
GO
ALTER TABLE [dbo].[AnhSanPham]  WITH CHECK ADD  CONSTRAINT [CK_AnhSanPham_ThuTu] CHECK  (([ThuTu]>=(0)))
GO
ALTER TABLE [dbo].[AnhSanPham] CHECK CONSTRAINT [CK_AnhSanPham_ThuTu]
GO
ALTER TABLE [dbo].[BannerTrangChu]  WITH CHECK ADD  CONSTRAINT [CK_BannerTrangChu_ThuTu] CHECK  (([ThuTu]>=(0)))
GO
ALTER TABLE [dbo].[BannerTrangChu] CHECK CONSTRAINT [CK_BannerTrangChu_ThuTu]
GO
ALTER TABLE [dbo].[BienTheSanPham]  WITH CHECK ADD  CONSTRAINT [CK_BienTheSanPham_Ton] CHECK  (([SoLuongTon]>=(0)))
GO
ALTER TABLE [dbo].[BienTheSanPham] CHECK CONSTRAINT [CK_BienTheSanPham_Ton]
GO
ALTER TABLE [dbo].[ChiTietDonHang]  WITH CHECK ADD  CONSTRAINT [CK_ChiTietDonHang_DonGia] CHECK  (([DonGia]>=(0)))
GO
ALTER TABLE [dbo].[ChiTietDonHang] CHECK CONSTRAINT [CK_ChiTietDonHang_DonGia]
GO
ALTER TABLE [dbo].[ChiTietDonHang]  WITH CHECK ADD  CONSTRAINT [CK_ChiTietDonHang_SoLuong] CHECK  (([SoLuong]>=(1)))
GO
ALTER TABLE [dbo].[ChiTietDonHang] CHECK CONSTRAINT [CK_ChiTietDonHang_SoLuong]
GO
ALTER TABLE [dbo].[ChiTietGioHang]  WITH CHECK ADD  CONSTRAINT [CK_ChiTietGioHang_SoLuong] CHECK  (([SoLuong]>=(1)))
GO
ALTER TABLE [dbo].[ChiTietGioHang] CHECK CONSTRAINT [CK_ChiTietGioHang_SoLuong]
GO
ALTER TABLE [dbo].[DanhGiaSanPham]  WITH CHECK ADD  CONSTRAINT [CK_DanhGiaSanPham_SoSao] CHECK  (([SoSao]>=(1) AND [SoSao]<=(5)))
GO
ALTER TABLE [dbo].[DanhGiaSanPham] CHECK CONSTRAINT [CK_DanhGiaSanPham_SoSao]
GO
ALTER TABLE [dbo].[DonHang]  WITH CHECK ADD  CONSTRAINT [CK_DonHang_CouponSnapshot] CHECK  (([MaMaGiamGia] IS NULL AND [CodeMaGiamGiaSnapshot] IS NULL OR [MaMaGiamGia] IS NOT NULL AND [CodeMaGiamGiaSnapshot] IS NOT NULL))
GO
ALTER TABLE [dbo].[DonHang] CHECK CONSTRAINT [CK_DonHang_CouponSnapshot]
GO
ALTER TABLE [dbo].[DonHang]  WITH CHECK ADD  CONSTRAINT [CK_DonHang_Tien] CHECK  (([TongTien]>=(0) AND [TienGiam]>=(0) AND [PhiShip]>=(0) AND [TongTien]>=[TienGiam]))
GO
ALTER TABLE [dbo].[DonHang] CHECK CONSTRAINT [CK_DonHang_Tien]
GO
ALTER TABLE [dbo].[DonHang]  WITH CHECK ADD  CONSTRAINT [CK_DonHang_TrangThaiTT] CHECK  (([TrangThaiThanhToan]='Refunded' OR [TrangThaiThanhToan]='Failed' OR [TrangThaiThanhToan]='Paid' OR [TrangThaiThanhToan]='Unpaid'))
GO
ALTER TABLE [dbo].[DonHang] CHECK CONSTRAINT [CK_DonHang_TrangThaiTT]
GO
ALTER TABLE [dbo].[KhuyenMai]  WITH CHECK ADD  CONSTRAINT [CK_KhuyenMai_GiamToiDa] CHECK  (([GiamToiDa] IS NULL OR [GiamToiDa]>(0)))
GO
ALTER TABLE [dbo].[KhuyenMai] CHECK CONSTRAINT [CK_KhuyenMai_GiamToiDa]
GO
ALTER TABLE [dbo].[KhuyenMai]  WITH CHECK ADD  CONSTRAINT [CK_KhuyenMai_GiaTri] CHECK  (([LoaiGiamGia]='FIXED_AMOUNT' AND [GiaTriGiam]>(0) OR [LoaiGiamGia]='PERCENTAGE' AND [GiaTriGiam]>(0) AND [GiaTriGiam]<=(100)))
GO
ALTER TABLE [dbo].[KhuyenMai] CHECK CONSTRAINT [CK_KhuyenMai_GiaTri]
GO
ALTER TABLE [dbo].[KhuyenMai]  WITH CHECK ADD  CONSTRAINT [CK_KhuyenMai_Loai] CHECK  (([LoaiGiamGia]='PERCENTAGE' OR [LoaiGiamGia]='FIXED_AMOUNT'))
GO
ALTER TABLE [dbo].[KhuyenMai] CHECK CONSTRAINT [CK_KhuyenMai_Loai]
GO
ALTER TABLE [dbo].[KhuyenMai]  WITH CHECK ADD  CONSTRAINT [CK_KhuyenMai_Ngay] CHECK  (([KetThuc]>[BatDau]))
GO
ALTER TABLE [dbo].[KhuyenMai] CHECK CONSTRAINT [CK_KhuyenMai_Ngay]
GO
ALTER TABLE [dbo].[MaGiamGia]  WITH CHECK ADD  CONSTRAINT [CK_MaGiamGia_SoLan]
CHECK (([SoLanToiDa]>=(1) AND [SoLanDaDung]>=(0) AND [SoLanDaDung]<=[SoLanToiDa]))
GO
ALTER TABLE [dbo].[MaGiamGia] CHECK CONSTRAINT [CK_MaGiamGia_SoLan]
GO

ALTER TABLE [dbo].[MaGiamGia]  WITH CHECK ADD  CONSTRAINT [CK_MaGiamGia_DungLuc]
CHECK (([SoLanDaDung]=(0) AND [DungLuc] IS NULL OR [SoLanDaDung]>(0) AND [DungLuc] IS NOT NULL))
GO
ALTER TABLE [dbo].[MaGiamGia] CHECK CONSTRAINT [CK_MaGiamGia_DungLuc]
GO

ALTER TABLE [dbo].[MaGiamGia]  WITH CHECK ADD  CONSTRAINT [CK_MaGiamGia_HetHan] CHECK  (([HetHanLuc]>[TaoLuc]))
GO
ALTER TABLE [dbo].[MaGiamGia] CHECK CONSTRAINT [CK_MaGiamGia_HetHan]
GO
ALTER TABLE [dbo].[NguoiDung]  WITH CHECK ADD  CONSTRAINT [CK_NguoiDung_CoThongTinDangNhap] CHECK  (([GoogleId] IS NOT NULL OR [TenDangNhap] IS NOT NULL AND [MatKhauHash] IS NOT NULL))
GO
ALTER TABLE [dbo].[NguoiDung] CHECK CONSTRAINT [CK_NguoiDung_CoThongTinDangNhap]
GO
ALTER TABLE [dbo].[SanPham]  WITH CHECK ADD  CONSTRAINT [CK_SanPham_Gia] CHECK  (([GiaGoc]>=(0)))
GO
ALTER TABLE [dbo].[SanPham] CHECK CONSTRAINT [CK_SanPham_Gia]
GO
ALTER TABLE [dbo].[ThongBao]  WITH CHECK ADD  CONSTRAINT [CK_ThongBao_DocLuc] CHECK  (([DaDoc]=(0) AND [DocLuc] IS NULL OR [DaDoc]=(1) AND [DocLuc] IS NOT NULL))
GO
ALTER TABLE [dbo].[ThongBao] CHECK CONSTRAINT [CK_ThongBao_DocLuc]
GO
ALTER TABLE [dbo].[TrangThaiDonHang]  WITH CHECK ADD  CONSTRAINT [CK_TrangThaiDonHang_ThuTu] CHECK  (([ThuTu]>=(1)))
GO
ALTER TABLE [dbo].[TrangThaiDonHang] CHECK CONSTRAINT [CK_TrangThaiDonHang_ThuTu]
GO
/****** Object:  StoredProcedure [dbo].[sp_RebuildProductPromotionsCache]    Script Date: 2/26/2026 2:57:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE   PROCEDURE [dbo].[sp_RebuildProductPromotionsCache]
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    DECLARE @Now DATETIME2(0) = SYSUTCDATETIME();

    BEGIN TRAN;

        TRUNCATE TABLE dbo.ProductPromotions;

        ;WITH ActivePromo AS (
            SELECT km.MaKhuyenMai, km.LoaiGiamGia, km.GiaTriGiam, km.GiamToiDa, km.UuTien
            FROM dbo.KhuyenMai km
            WHERE km.KichHoat = 1
              AND km.BatDau <= @Now
              AND km.KetThuc >  @Now
        ),
        VariantPrice AS (
            SELECT
                bt.MaBienThe,
                sp.MaSanPham,
                CAST(sp.GiaGoc + bt.DieuChinhGia AS DECIMAL(18,2)) AS GiaHienTai
            FROM dbo.BienTheSanPham bt
            JOIN dbo.SanPham sp ON sp.MaSanPham = bt.MaSanPham
            WHERE sp.HoatDong = 1 AND bt.HoatDong = 1
        ),
        Candidate AS (
            SELECT
                vp.MaBienThe,
                vp.MaSanPham,
                ap.MaKhuyenMai,
                ap.UuTien,
                vp.GiaHienTai AS GiaGoc,
                CAST(
                    CASE
                        WHEN ap.LoaiGiamGia = 'PERCENTAGE' THEN
                            CASE
                                WHEN ap.GiamToiDa IS NULL THEN (vp.GiaHienTai * ap.GiaTriGiam / 100.0)
                                ELSE
                                    CASE
                                        WHEN (vp.GiaHienTai * ap.GiaTriGiam / 100.0) > ap.GiamToiDa THEN ap.GiamToiDa
                                        ELSE (vp.GiaHienTai * ap.GiaTriGiam / 100.0)
                                    END
                            END
                        WHEN ap.LoaiGiamGia = 'FIXED_AMOUNT' THEN
                            CASE
                                WHEN ap.GiaTriGiam > vp.GiaHienTai THEN vp.GiaHienTai
                                ELSE ap.GiaTriGiam
                            END
                        ELSE 0
                    END
                AS DECIMAL(18,2)) AS SoTienGiam
            FROM VariantPrice vp
            JOIN dbo.SanPhamKhuyenMai spkm ON spkm.MaSanPham = vp.MaSanPham
            JOIN ActivePromo ap ON ap.MaKhuyenMai = spkm.MaKhuyenMai
        ),
        Ranked AS (
            SELECT
                c.*,
                CAST(c.GiaGoc - c.SoTienGiam AS DECIMAL(18,2)) AS GiaSauGiam,
                ROW_NUMBER() OVER (
                    PARTITION BY c.MaBienThe
                    ORDER BY c.SoTienGiam DESC, c.UuTien DESC, c.MaKhuyenMai ASC
                ) AS rn
            FROM Candidate c
        )
        INSERT INTO dbo.ProductPromotions(MaBienThe, MaSanPham, MaKhuyenMai, GiaGoc, SoTienGiam, GiaSauGiam, CapNhatLuc)
        SELECT
            vp.MaBienThe,
            vp.MaSanPham,
            r.MaKhuyenMai,
            vp.GiaHienTai,
            COALESCE(r.SoTienGiam, 0),
            COALESCE(r.GiaSauGiam, vp.GiaHienTai),
            @Now
        FROM VariantPrice vp
        LEFT JOIN Ranked r
               ON r.MaBienThe = vp.MaBienThe
              AND r.rn = 1;

    COMMIT;
END
GO
USE [master]
GO
ALTER DATABASE [HeThongBanHangThoiTrangDB] SET  READ_WRITE 
GO

USE [HeThongBanHangThoiTrangDB];
GO

-- Index tối ưu truy vấn list sản phẩm theo giá sau giảm
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_ProductPromotions_MaSanPham_GiaSauGiam'
      AND object_id = OBJECT_ID('dbo.ProductPromotions')
)
BEGIN
    CREATE NONCLUSTERED INDEX [IX_ProductPromotions_MaSanPham_GiaSauGiam]
    ON [dbo].[ProductPromotions]([MaSanPham], [GiaSauGiam])
    INCLUDE ([GiaGoc], [SoTienGiam], [MaKhuyenMai], [CapNhatLuc]);
END
GO

-- Index để lấy ảnh chính nhanh (AnhChinh = 1)
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_AnhSanPham_MaSanPham_AnhChinh'
      AND object_id = OBJECT_ID('dbo.AnhSanPham')
)
BEGIN
    CREATE NONCLUSTERED INDEX [IX_AnhSanPham_MaSanPham_AnhChinh]
    ON [dbo].[AnhSanPham]([MaSanPham], [AnhChinh])
    INCLUDE ([UrlAnh], [ThuTu]);
END
GO

/*
============================================================
Seed data tối thiểu cho DEV (tuần 4)
- VaiTro (Admin/User)
- TrangThaiDonHang (đảm bảo có MaTrangThai = 4 là "Thành công")
============================================================
*/
USE [HeThongBanHangThoiTrangDB];
GO

-- VaiTro
IF NOT EXISTS (SELECT 1 FROM dbo.VaiTro WHERE MaVaiTro = 1)
    INSERT dbo.VaiTro (MaVaiTro, TenVaiTro) VALUES (1, N'Admin');

IF NOT EXISTS (SELECT 1 FROM dbo.VaiTro WHERE MaVaiTro = 2)
    INSERT dbo.VaiTro (MaVaiTro, TenVaiTro) VALUES (2, N'User');
GO

-- TrangThaiDonHang
IF NOT EXISTS (SELECT 1 FROM dbo.TrangThaiDonHang WHERE MaTrangThai = 1)
    INSERT dbo.TrangThaiDonHang (MaTrangThai, TenTrangThai, ThuTu) VALUES (1, N'Mới tạo', 1);

IF NOT EXISTS (SELECT 1 FROM dbo.TrangThaiDonHang WHERE MaTrangThai = 2)
    INSERT dbo.TrangThaiDonHang (MaTrangThai, TenTrangThai, ThuTu) VALUES (2, N'Đã thanh toán', 2);

IF NOT EXISTS (SELECT 1 FROM dbo.TrangThaiDonHang WHERE MaTrangThai = 3)
    INSERT dbo.TrangThaiDonHang (MaTrangThai, TenTrangThai, ThuTu) VALUES (3, N'Đang giao', 3);

-- IMPORTANT: mốc "Thành công" đang được dùng ở thống kê (MaTrangThai = 4)
IF NOT EXISTS (SELECT 1 FROM dbo.TrangThaiDonHang WHERE MaTrangThai = 4)
    INSERT dbo.TrangThaiDonHang (MaTrangThai, TenTrangThai, ThuTu) VALUES (4, N'Thành công', 4);

IF NOT EXISTS (SELECT 1 FROM dbo.TrangThaiDonHang WHERE MaTrangThai = 5)
    INSERT dbo.TrangThaiDonHang (MaTrangThai, TenTrangThai, ThuTu) VALUES (5, N'Đã hủy', 5);
GO




/* ============================================================
   15) SEED SAN PHAM MAU (20 sp) + ANH + 4 BIEN THE / SP (DEV)
   - Anh dung placeholder tu picsum.photos (co the thay bang CDN cua may)
   - Re-run safe (IF NOT EXISTS)
   ============================================================ */

USE [HeThongBanHangThoiTrangDB];
GO

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

BEGIN TRY
    BEGIN TRAN;

    DECLARE @Now DATETIME2(0) = SYSUTCDATETIME();

    /* 1) DanhMuc (neu chua co) */
    IF NOT EXISTS (SELECT 1 FROM dbo.DanhMuc WHERE Slug = 'ao')
        INSERT dbo.DanhMuc (TenDanhMuc, Slug, MaDanhMucCha) VALUES (N'Áo', 'ao', NULL);

    IF NOT EXISTS (SELECT 1 FROM dbo.DanhMuc WHERE Slug = 'quan')
        INSERT dbo.DanhMuc (TenDanhMuc, Slug, MaDanhMucCha) VALUES (N'Quần', 'quan', NULL);

    IF NOT EXISTS (SELECT 1 FROM dbo.DanhMuc WHERE Slug = 'vay')
        INSERT dbo.DanhMuc (TenDanhMuc, Slug, MaDanhMucCha) VALUES (N'Váy', 'vay', NULL);

    IF NOT EXISTS (SELECT 1 FROM dbo.DanhMuc WHERE Slug = 'do-ni')
        INSERT dbo.DanhMuc (TenDanhMuc, Slug, MaDanhMucCha) VALUES (N'Đồ nỉ', 'do-ni', NULL);

    IF NOT EXISTS (SELECT 1 FROM dbo.DanhMuc WHERE Slug = 'ao-khoac')
        INSERT dbo.DanhMuc (TenDanhMuc, Slug, MaDanhMucCha) VALUES (N'Áo khoác', 'ao-khoac', NULL);

    IF NOT EXISTS (SELECT 1 FROM dbo.DanhMuc WHERE Slug = 'phu-kien')
        INSERT dbo.DanhMuc (TenDanhMuc, Slug, MaDanhMucCha) VALUES (N'Phụ kiện', 'phu-kien', NULL);

    /* 2) KichCo + MauSac (toi thieu de tao bien the) */
    IF NOT EXISTS (SELECT 1 FROM dbo.KichCo WHERE TenKichCo = 'M') INSERT dbo.KichCo(TenKichCo) VALUES ('M');
    IF NOT EXISTS (SELECT 1 FROM dbo.KichCo WHERE TenKichCo = 'L') INSERT dbo.KichCo(TenKichCo) VALUES ('L');

    IF NOT EXISTS (SELECT 1 FROM dbo.MauSac WHERE TenMau = N'Đen')   INSERT dbo.MauSac(TenMau, MaHex) VALUES (N'Đen',   '#000000');
    IF NOT EXISTS (SELECT 1 FROM dbo.MauSac WHERE TenMau = N'Trắng') INSERT dbo.MauSac(TenMau, MaHex) VALUES (N'Trắng', '#FFFFFF');

    DECLARE @SizeM INT = (SELECT MaKichCo FROM dbo.KichCo WHERE TenKichCo = 'M');
    DECLARE @SizeL INT = (SELECT MaKichCo FROM dbo.KichCo WHERE TenKichCo = 'L');
    DECLARE @ColorBlack INT = (SELECT MaMauSac FROM dbo.MauSac WHERE TenMau = N'Đen');
    DECLARE @ColorWhite INT = (SELECT MaMauSac FROM dbo.MauSac WHERE TenMau = N'Trắng');

    /* 3) SanPham */
    DECLARE @Products TABLE (
        Slug VARCHAR(200) NOT NULL PRIMARY KEY,
        TenSanPham NVARCHAR(200) NOT NULL,
        DanhMucSlug VARCHAR(100) NOT NULL,
        MoTa NVARCHAR(500) NULL,
        GiaGoc DECIMAL(18,2) NOT NULL,
        SkuPrefix VARCHAR(20) NOT NULL
    );

    INSERT INTO @Products(Slug, TenSanPham, DanhMucSlug, MoTa, GiaGoc, SkuPrefix)
    VALUES ('ao-thun-basic-cotton-240gsm', N'Áo thun basic cotton 240gsm', 'ao', N'Cotton dày 240gsm, form gọn, mặc hằng ngày.', 199000.00, 'SP001');

    INSERT INTO @Products(Slug, TenSanPham, DanhMucSlug, MoTa, GiaGoc, SkuPrefix)
    VALUES ('ao-thun-oversize-graphic', N'Áo thun oversize graphic', 'ao', N'Oversize thoải mái, in graphic nổi bật.', 239000.00, 'SP002');

    INSERT INTO @Products(Slug, TenSanPham, DanhMucSlug, MoTa, GiaGoc, SkuPrefix)
    VALUES ('ao-polo-pique', N'Áo polo pique', 'ao', N'Vải pique thoáng, cổ đứng chuẩn chỉnh.', 279000.00, 'SP003');

    INSERT INTO @Products(Slug, TenSanPham, DanhMucSlug, MoTa, GiaGoc, SkuPrefix)
    VALUES ('ao-so-mi-oxford', N'Áo sơ mi Oxford', 'ao', N'Oxford dệt chéo, lịch sự mà vẫn trẻ.', 329000.00, 'SP004');

    INSERT INTO @Products(Slug, TenSanPham, DanhMucSlug, MoTa, GiaGoc, SkuPrefix)
    VALUES ('ao-so-mi-linen', N'Áo sơ mi linen', 'ao', N'Linen mát, hợp đi biển và đi làm.', 349000.00, 'SP005');

    INSERT INTO @Products(Slug, TenSanPham, DanhMucSlug, MoTa, GiaGoc, SkuPrefix)
    VALUES ('quan-jean-slim', N'Quần jean slim fit', 'quan', N'Slim fit tôn dáng, co giãn nhẹ.', 399000.00, 'SP006');

    INSERT INTO @Products(Slug, TenSanPham, DanhMucSlug, MoTa, GiaGoc, SkuPrefix)
    VALUES ('quan-jean-straight', N'Quần jean straight', 'quan', N'Ống đứng cổ điển, dễ phối đồ.', 419000.00, 'SP007');

    INSERT INTO @Products(Slug, TenSanPham, DanhMucSlug, MoTa, GiaGoc, SkuPrefix)
    VALUES ('quan-short-kaki', N'Quần short kaki', 'quan', N'Kaki đứng form, mặc mát ngày nóng.', 249000.00, 'SP008');

    INSERT INTO @Products(Slug, TenSanPham, DanhMucSlug, MoTa, GiaGoc, SkuPrefix)
    VALUES ('chan-vay-chu-a', N'Chân váy chữ A', 'vay', N'Dáng chữ A, tôn eo, dễ mix áo.', 289000.00, 'SP009');

    INSERT INTO @Products(Slug, TenSanPham, DanhMucSlug, MoTa, GiaGoc, SkuPrefix)
    VALUES ('vay-maxi-hoa', N'Váy maxi hoa', 'vay', N'Maxi nhẹ, hoạ tiết hoa, bay bổng.', 459000.00, 'SP010');

    INSERT INTO @Products(Slug, TenSanPham, DanhMucSlug, MoTa, GiaGoc, SkuPrefix)
    VALUES ('hoodie-ni', N'Hoodie nỉ basic', 'do-ni', N'Nỉ bông ấm, logo tối giản.', 389000.00, 'SP011');

    INSERT INTO @Products(Slug, TenSanPham, DanhMucSlug, MoTa, GiaGoc, SkuPrefix)
    VALUES ('sweater-len', N'Sweater len mỏng', 'do-ni', N'Len mỏng, mặc layer cực ổn.', 359000.00, 'SP012');

    INSERT INTO @Products(Slug, TenSanPham, DanhMucSlug, MoTa, GiaGoc, SkuPrefix)
    VALUES ('ao-khoac-bomber', N'Áo khoác bomber', 'ao-khoac', N'Bomber nhẹ, khoá kéo, form gọn.', 499000.00, 'SP013');

    INSERT INTO @Products(Slug, TenSanPham, DanhMucSlug, MoTa, GiaGoc, SkuPrefix)
    VALUES ('ao-khoac-denim', N'Áo khoác denim', 'ao-khoac', N'Denim bền, càng mặc càng đẹp.', 529000.00, 'SP014');

    INSERT INTO @Products(Slug, TenSanPham, DanhMucSlug, MoTa, GiaGoc, SkuPrefix)
    VALUES ('tui-tote-canvas', N'Túi tote canvas', 'phu-kien', N'Canvas dày, đựng laptop vừa đủ.', 179000.00, 'SP015');

    INSERT INTO @Products(Slug, TenSanPham, DanhMucSlug, MoTa, GiaGoc, SkuPrefix)
    VALUES ('non-bucket', N'Nón bucket', 'phu-kien', N'Bucket vành vừa, che nắng ổn.', 159000.00, 'SP016');

    INSERT INTO @Products(Slug, TenSanPham, DanhMucSlug, MoTa, GiaGoc, SkuPrefix)
    VALUES ('that-lung-da', N'Thắt lưng da', 'phu-kien', N'Da PU/da tổng hợp, khoá kim.', 199000.00, 'SP017');

    INSERT INTO @Products(Slug, TenSanPham, DanhMucSlug, MoTa, GiaGoc, SkuPrefix)
    VALUES ('vo-co-cao', N'Vớ cổ cao', 'phu-kien', N'Cotton co giãn, cổ cao thể thao.', 59000.00, 'SP018');

    INSERT INTO @Products(Slug, TenSanPham, DanhMucSlug, MoTa, GiaGoc, SkuPrefix)
    VALUES ('ao-tank-top', N'Áo tank top', 'ao', N'Tank top ôm vừa, thấm hút tốt.', 149000.00, 'SP019');

    INSERT INTO @Products(Slug, TenSanPham, DanhMucSlug, MoTa, GiaGoc, SkuPrefix)
    VALUES ('quan-jogger', N'Quần jogger', 'quan', N'Jogger bo gấu, mặc đi chơi/đi tập.', 329000.00, 'SP020');

    ;WITH Src AS (
        SELECT p.Slug, p.TenSanPham, p.MoTa, p.GiaGoc, dm.MaDanhMuc
        FROM @Products p
        JOIN dbo.DanhMuc dm ON dm.Slug = p.DanhMucSlug
    )
    MERGE dbo.SanPham AS t
    USING Src AS s
       ON t.Slug = s.Slug
    WHEN NOT MATCHED THEN
        INSERT (TenSanPham, Slug, MoTa, GiaGoc, MaDanhMuc, AnhDaiDien)
        VALUES (s.TenSanPham, s.Slug, s.MoTa, s.GiaGoc, s.MaDanhMuc, NULL);

    /* 4) AnhSanPham (3 anh / sp, 1 anh chinh) */
    ;WITH ImgSrc AS (
        SELECT
            sp.MaSanPham,
            x.ThuTu,
            x.AnhChinh,
            x.UrlAnh
        FROM @Products p
        JOIN dbo.SanPham sp ON sp.Slug = p.Slug
        CROSS APPLY (VALUES
            (1, CAST(1 AS bit), CONCAT('https://picsum.photos/seed/', p.Slug, '-1/900/1200')),
            (2, CAST(0 AS bit), CONCAT('https://picsum.photos/seed/', p.Slug, '-2/900/1200')),
            (3, CAST(0 AS bit), CONCAT('https://picsum.photos/seed/', p.Slug, '-3/900/1200'))
        ) x(ThuTu, AnhChinh, UrlAnh)
    )
    INSERT dbo.AnhSanPham(MaSanPham, UrlAnh, ThuTu, AnhChinh)
    SELECT i.MaSanPham, i.UrlAnh, i.ThuTu, i.AnhChinh
    FROM ImgSrc i
    WHERE NOT EXISTS (
        SELECT 1 FROM dbo.AnhSanPham a
        WHERE a.MaSanPham = i.MaSanPham
          AND a.UrlAnh = i.UrlAnh
    )
      AND (
        i.AnhChinh = 0
        OR NOT EXISTS (
            SELECT 1 FROM dbo.AnhSanPham a2
            WHERE a2.MaSanPham = i.MaSanPham
              AND a2.AnhChinh = 1
        )
      );

    /* 5) BienTheSanPham (4 bien the / sp: Den/Trang x M/L) */
    ;WITH VarSrc AS (
        SELECT
            sp.MaSanPham,
            c.MaMauSac,
            k.MaKichCo,
            CONCAT(p.SkuPrefix, '-', c.CodeMau, '-', k.CodeSize) AS SKU,
            CAST(50 AS int) AS SoLuongTon,
            CAST(0 AS decimal(18,2)) AS DieuChinhGia
        FROM @Products p
        JOIN dbo.SanPham sp ON sp.Slug = p.Slug
        CROSS JOIN (VALUES
            ('BLK', @ColorBlack),
            ('WHT', @ColorWhite)
        ) c(CodeMau, MaMauSac)
        CROSS JOIN (VALUES
            ('M', @SizeM),
            ('L', @SizeL)
        ) k(CodeSize, MaKichCo)
    )
    INSERT dbo.BienTheSanPham(MaSanPham, MaMauSac, MaKichCo, SKU, SoLuongTon, DieuChinhGia)
    SELECT v.MaSanPham, v.MaMauSac, v.MaKichCo, v.SKU, v.SoLuongTon, v.DieuChinhGia
    FROM VarSrc v
    WHERE NOT EXISTS (
        SELECT 1 FROM dbo.BienTheSanPham bt
        WHERE bt.MaSanPham = v.MaSanPham
          AND bt.MaMauSac = v.MaMauSac
          AND bt.MaKichCo = v.MaKichCo
    )
      AND NOT EXISTS (
        SELECT 1 FROM dbo.BienTheSanPham bt2
        WHERE bt2.SKU = v.SKU
      );

    COMMIT;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK;
    THROW;
END CATCH
GO

-- Quick check
SELECT TOP (20)
    sp.MaSanPham, sp.TenSanPham, sp.Slug, sp.GiaGoc, dm.TenDanhMuc,
    img.UrlAnh AS AnhChinh
FROM dbo.SanPham sp
JOIN dbo.DanhMuc dm ON dm.MaDanhMuc = sp.MaDanhMuc
OUTER APPLY (
    SELECT TOP 1 UrlAnh
    FROM dbo.AnhSanPham a
    WHERE a.MaSanPham = sp.MaSanPham AND a.AnhChinh = 1
    ORDER BY a.ThuTu ASC
) img
ORDER BY sp.MaSanPham DESC;
GO